name: Lint and Type Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      
      - name: Format check with ruff
        run: uvx ruff format --check

      - name: Lint with ruff
        run: uvx ruff check

      - name: Type check with mypy
        run: uvx mypy .
